AWSTemplateFormatVersion: '2010-09-09'
Description: ECR Repositories for Microservices images.

Parameters:
  ProjectNamespace:
    Type: String
    Default: nusiss-team-1-voc
    Description: The prefix for your repositories

Resources:
  ListingServiceRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "${ProjectNamespace}/tcgm-listing"
      LifecyclePolicy:
        LifecyclePolicyText: |
          {"rules":[{"rulePriority":1,"description":"Keep last 10","selection":{"tagStatus":"any","countType":"imageCountMoreThan","countNumber":50},"action":{"type":"expire"}}]}

  MessagingServiceRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "${ProjectNamespace}/tcgm-messaging"
      LifecyclePolicy:
        LifecyclePolicyText: |
          {"rules":[{"rulePriority":1,"description":"Keep last 10","selection":{"tagStatus":"any","countType":"imageCountMoreThan","countNumber":50},"action":{"type":"expire"}}]}

  WebRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "${ProjectNamespace}/tcgm-web"
      LifecyclePolicy:
        LifecyclePolicyText: |
          {"rules":[{"rulePriority":1,"description":"Keep last 10","selection":{"tagStatus":"any","countType":"imageCountMoreThan","countNumber":50},"action":{"type":"expire"}}]}

Outputs:
  ListingServiceRepoUri:
    Value: !GetAtt ListingServiceRepository.RepositoryUri
  MessagingServiceRepoUri:
    Value: !GetAtt MessagingServiceRepository.RepositoryUri
  WebRepoUri:
    Value: !GetAtt WebRepository.RepositoryUri
