name: "Backend | Env: Develop"

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - "backend/**"

concurrency:
  group: app-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    uses: ./.github/workflows/app-deploy.yml
    with:
      image_tag_prefix: develop
      auto_deploy: true
    secrets: inherit
