name: "CI: Messaging Service (prod)"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "backend/messaging-service/**"

concurrency:
  group: messaging-ci-prod-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/app-deploy.yml
    with:
      service: messaging
      image_tag_prefix: prod
    secrets: inherit
