name: "CI: Messaging Service (dev)"

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - "backend/messaging-service/**"

concurrency:
  group: messaging-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    uses: ./.github/workflows/app-deploy.yml
    with:
      service: messaging
      image_tag_prefix: develop
      auto_deploy: true
    secrets: inherit
