name: "CI: Frontend (dev)"

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - "frontend/**"

concurrency:
  group: web-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    uses: ./.github/workflows/web-deploy.yml
    with:
      environment: dev
      image_tag_prefix: develop
      auto_deploy: true
    secrets: inherit
